# Generated by Django 4.2 on 2023-04-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.PositiveIntegerField()),
                ('name', models.CharField(db_comment='Name of Student', max_length=20)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
